export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const AUTHENTICATE_THE_USER = 'AUTHENTICATE_THE_USER';
export const SET_TOKENS = 'SET_TOKENS';
export const LOG_OUT = 'LOG_OUT';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const SWITCH_VIEW_CATEGORY = 'SWITCH_VIEW_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const INCREMENT_CURRENT_CATEGORY_TODO_COUNTER =
  'INCREMENT_CURRENT_CATEGORY_TODO_COUNTER';
export const DECREMENT_CURRENT_CATEGORY_TODO_COUNTER =
  'DECREMENT_CURRENT_CATEGORY_TODO_COUNTER';
